### ISSUE TITLE
Use the new Kino.Process supervision tree visualizer to improve the supervisors reading material.

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#141]

**Comment by TwistingTwists** [comment]
https://github.com/DockYard-Academy/beta_curriculum/blob/main/exercises/supervised_stack.livemd

Does this file needs to be worked on for above issue?

**Comment by BrooklinJazz** [comment]
> https://github.com/DockYard-Academy/beta_curriculum/blob/main/exercises/supervised_stack.livemd
> 
> Does this file needs to be worked on for above issue?

Apologies for missing your comment. This was an internal ticket, it's now been resolved. It was the reading material `supervisors.livemd` that needed to be modified.
