### ISSUE TITLE
Create a Script to Ensure README outline remains up to date with `start.livemd`.

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#151]
Using the `File` module we can read the `start.livemd` file which contains the outline of the project, then use this file to automatically generate the Curriculum Outline section of the README.

**Comment by BrooklinJazz** [comment]
#153 could cause issues for this.

**Comment by aayushmau5** [comment]
@BrooklinJazz I can work on this :)

**Comment by BrooklinJazz** [comment]
We might want to wait to work on this until the start.livemd structure is stable 🤔 Alternatively the script could simply grab heading 2s and heading 3s which even if we change the structure, should provide a proper outline.

We'll also want to be careful not to overwrite other README contents such as the troubleshooting section.

**Comment by aayushmau5** [comment]
> We might want to wait to work on this until the start.livemd structure is stable. Alternatively the script could simply grab heading 2s and heading 3s which even if we change the structure, should provide a proper outline.

We can go with the alternative approach. But let me know if we should wait it out a bit.

> We'll also want to be careful not to overwrite other README contents such as the troubleshooting section.

Yeah, for this, I think we should have a comment section.

```
<!-- table_of_content_start -->
<!-- table_of_content_end -->
```
So, we modify only this section of README.

**Comment by BrooklinJazz** [comment]
I'm planning to re-write start.livemd to move away from time-based and instead be topic-based.

I'll move that up as a priority and finish it today. Let's pause this issue until I'm done.

**Comment by aayushmau5** [comment]
Sure!

**Comment by BrooklinJazz** [comment]
@aayushmau5 I've finished `start.livemd` so we should be ready to go on this script :D I decided to keep the weeks in each section for now.

**Comment by aayushmau5** [comment]
Awesome! I'll start working on it.

**Comment by aayushmau5** [comment]
@BrooklinJazz How do we want the outline to look like?

So current `start.livemd` outline is as follows:
```
## Week 1: Core Syntax

### 1. Course Tools

* Reading
  * [Command Line](reading/command_line.livemd)
  * [Git](reading/git.livemd)
  * [Livebook](reading/livebook.livemd)
  * [Code Editors](reading/code_editors.livemd)
* Exercises
  * [Command Line Family Tree](exercises/command_line_family_tree.livemd)
  * [Livebook Recovery](exercises/livebook_recovery.livemd)
  * [GitHub Engineering Journal](exercises/github_engineering_journal.livemd)
  * [GitHub Collab](exercises/github_collab.livemd)

... and so on.
 ```

Based on current README, I guess I just have to read `##` and `###` tags and generate an outline, right?

Do we want to add more info?

**Comment by BrooklinJazz** [comment]
I think just the headings is perfect but I'm open to other ideas.

**Comment by aayushmau5** [comment]
Think I'll go with heading for now. Adding individual reading/exercise material outline might feel too cluttered.

**Comment by BrooklinJazz** [comment]
@aayushmau5 I agree. However, I had an idea I wanted to share of using `<details>` to organize the content. Something like this:

<details>
<summary><h3>1. Basics</h3></summary>
<ul>
  <li>Reading 1</li>
  <li>Reading 2</li>
  <li>Exercise 1</li>
  <li>Exercise 2</li>
</details>

Zero pressure to implement it. Not sure if it would be good or not, but I thought I'd mention it in case you think it's cool.

**Comment by BrooklinJazz** [comment]
Something about having the README being interactive feels very fun to me 😎
