### ISSUE TITLE
Include Git Instructions in each lesson.

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#153]
Ideally, students should regularly create pull requests for each day of material to develop familiarity with Git and GitHub.

The start of each day should include instructions on how to make a new branch.

```
$ git checkout -b week-1-day-1
```

Then each reading and exercise should include instructions on how to add, commit, and push changes.

## Commit Changes
```
$ git add reading/command_line.livemd
$ git commit -m "complete command line reading"
```

At the end of the day, students should make a PR, and merge their changes.

1. Make a pull request.
2. Merge the pull request.
3. Pull changes locally:
```
$ git push -u origin week-1-day-1
$ git checkout main
$ git pull
```

This may require changing the `start.livemd` to separate each day into its own `.livemd` file.

**Comment by aayushmau5** [comment]
I'd like to help with this :)

**Comment by BrooklinJazz** [comment]
That would be awesome! I want to update the **Setup** sections to the following:
```
## Setup

Follow the [Git Instructions](https://github.com/DockYard-Academy/beta_curriculum/wiki/Git-Instructions) before starting this lesson/exercise.
```

I don't think it's beneficial to include the `ea` instructions anymore.

**Comment by BrooklinJazz** [comment]
I think doing a simple find/replace to fix every setup section would be enough.

However, it should probably be committed from the Command Line and Git reading material.
There are also exercises/lessons that don't cause any changes in the curriculum that may be awkward 🤔

I'm also doubting if students should do this for every lesson/exercise, and instead do it for each day's worth of material. hmm.

**Comment by BrooklinJazz** [comment]
@aayushmau5 do you have any thoughts on if students should follow the git flow for each exercise, or at the start/end of the day?

**Comment by aayushmau5** [comment]
I think creating a PR at the end of the day should be good. But we could instruct students to create a commit after each exercise. So at the end of the day, they are number of small commits related to each day's exercises. What do you think?

**Comment by BrooklinJazz** [comment]
@aayushmau5 I really like that. Students would still get regular practice making PRs (one of the skills I often see underdeveloped in bootcamp developers), but it's more lightweight than making PR every exercise.

In that case, perhaps a single instruction at the end of each lesson/exercise would be enough. For example:

## Commit Your Progress

Run the following in your command line from the project folder to track and save your progress in a Git commit.

```
$ git add .
$ git commit -m "complete boolean operators exercise"
```

Then at the start and end of each day I can instruct students to create a branch and make a PR.

**Comment by aayushmau5** [comment]
Yeah. This is good. Should I start working on it then?

Add a "commit" instruction after each lesson/exercise(where necessary). 

And do I modify the setup instruction or add a PR instruction at the end of the day?

**Comment by BrooklinJazz** [comment]
We're good to start! Let me know if you have any questions.

I think we can omit branching and PR instructions in the curriculum itself for now. The start.livemd is likely to change significantly and I'm not sure if PRs are necessary for non-academy students going through the curriculum self-paced.

**Comment by aayushmau5** [comment]
@BrooklinJazz For each lesson and exercises, we have to add custom commit message, right?

I'm currently putting these commit instructions at the end of each lesson and exercise(except for week 1). Let me know if I'm going in the right direction, or not :)

**Comment by BrooklinJazz** [comment]
@aayushmau5 that's great!

We could probably write a .exs script to automate this and make life easier.

Feel free to push up a PR with [WIP] in the title to get early feedback.

**Comment by BrooklinJazz** [comment]
I can pair program with you if you'd like to talk about how to make the script.

**Comment by aayushmau5** [comment]
I'll try my hand at making the script. If I face any problem, I'll let you know :)
