### ISSUE TITLE
Fix FontAwesome setup in Home Page exercise

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#154]
The instructions for installing FontAwesome are incorrect in `exercises/home_page.livemd`.

```html
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
```

We need to either use a different icon library or add the correct FontAwesome instructions.

**Comment by crismxiex** [comment]
Seems like Fontawesome is now requiring to create an account and create something called "kit" before you start using it in a project, do you think it is still a good idea to use fontawesome? Or maybe look for another icon library?

**Comment by BrooklinJazz** [comment]
hmm, that's annoying! Seems like it's changed since I last used it. if there's a quicker option that doesn't require account creation we should use it. Or perhaps we should remove this from the Home Page exercise entirely 🤔

Do you recommend any other icon library? Maybe Remix would be good. I think that's what Livebook uses.

**Comment by crismxiex** [comment]
Lineicons could be a good alternative. Looking at their docs https://lineicons.com/docs/ it could be as easy as fontawesome was previously

**Comment by aayushmau5** [comment]
Was checking out this issue. I see that this has been done. 

I think this issue can be closed :)

**Comment by BrooklinJazz** [comment]
Thank you @aayushmau5 & @crismxiex
