### ISSUE TITLE
Replace calls to Utils.feedback with the new Tested Cell

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#170]
We need to replace all calls to `Utils.feedback` with the new smart cells.

There's the `TestedCell` which we can write tests directly in the livebook. See the Mad Libs exercise for an example.

![image](https://user-images.githubusercontent.com/14877564/181367656-2238940e-8bbe-404d-acc5-5076c3ea22c3.png)

There's also the `ExerciseCell` we can use to create custom smart cells. See `madlib.ex` and `exercise.ex` for an example. This has the added benefit of having the solution validated. However, it comes at the cost of creating a new smart cell (which could eventually be cumbersome in the Livebook Smart cell dropdown.)

Existing tests can be stolen and modified from `feedback.ex`. Some tests could use some work to produce simpler output for students to be able to read better.

**Comment by zorn** [comment]
@BrooklinJazz I believe this is the issue that you brought up at ElixirConf as something I might be able to help out with. Maybe we could pair over zoom, so I could verify what you are looking for, and then I'll give it a shot. 

If you want to grab some time, use this link: https://savvycal.com/zorn/chat

**Comment by BrooklinJazz** [comment]
I booked a time!

**Comment by zorn** [comment]
During our zoom call, after some demos and discussions, @BrooklinJazz shared that this work might not be as tightly shaped as it should be, so I'll be focusing on  #196 as a first PR goal which is a little more strait forward.

**Comment by BrooklinJazz** [comment]
We are moving away from the `TestedCell` library in favor of using doctests and `<details>` for hiding hints and solutions.

I have a few reasons for this:

- `TestedCell` displays only a single test failure instead of multiple for each feature.
- `TestedCell` has (AFAIK unsolvable) issues where warnings will be duplicated and previously defined variables cannot be accessed.

In the future, I think it could be interesting to
- Create a custom HTML formatter for Livebook
- Hide test code using a hidden cell
- Run tests on the press of a button

However, this requires a lot of work. so for now I'm going to move forward with using hints and doctests.
