### ISSUE TITLE
Create a new ValidatedForm smart cell to replace calls to `Utils.form`.

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#178]
Create a new Validated Form smart cell to replace calls to `Utils.form`.

Ultimately, I'd like to eventually remove the `Utils` project.

**Comment by mtvillwock** [comment]
Is this in reference to how incorrect answers for `Utils.form` questions only show positive confirmation (green background highlight) but not negative confirmation (red background highlight)? Or should I make a separate issue for that?
 
![Screen Shot 2022-08-05 at 1 55 43 PM](https://user-images.githubusercontent.com/8475488/183225010-e86cf161-fc21-4c25-ab3f-8d4649d55ca8.png)

**Comment by BrooklinJazz** [comment]
This is not in reference to any behavioral issues. This Issue means we need to create a new Smart Cell or `Kino.JS` component for these validated forms rather than calling `Utils.form/1`.

I'm not sure I agree that forms should have a negative confirmation but feel free to raise a separate issue, and we can discuss it!
My reasoning is:
- red feels bad.
- green confirms the answer is correct, and grey confirms the answer is wrong. I don't think it's an unclear experience for students, but I could be wrong!
- There's no submission to trigger red, so students would have to see a red background when they start typing. I suppose we could figure out how to submit the form to trigger color changes. However, I like the instant feedback and don't think it's a good tradeoff.
