### ISSUE TITLE
Fix formatting keybinds in the 1. Course tools / livebook

### ISSUE THREAD

**Issue by IntervalsCM** [DockYard-Academy/beta_curriculum#183]
![image](https://user-images.githubusercontent.com/106613029/181677596-968eba72-b05c-40fc-9a1d-6a61c2e619a2.png)
In the 1. Course Tools / Livebook part there's an instruction that indicates that the "Ctrl  + Shift + I " keybinding is used to format the code in livebook, however this keybind will prompt the browser element inspector to open

**Comment by BrooklinJazz** [comment]
Resolved in #184
