### ISSUE TITLE
Utils.animate/1 never stops running in Livebook

### ISSUE THREAD

**Issue by mtvillwock** [DockYard-Academy/beta_curriculum#196]
**Describe the issue**
Code cells using `Utils.animate/1` in Livebook never stop computing.

**Reproduction Steps (If Applicable)**
1. Go to 'Arithmetic' section of curriculum in Livebook
1. Scroll down to 'Integers'
1. In the "Your Turn" section, click 'Evaluate' for the code cell (`Utils.animate(:biggest_integer)`
1. Watch as the numbers start increasing and never stop

**Expected behavior**
`Utils.animate/1` can/does stop at some point.

Possible solutions:
- `Utils.stop_animate/1`
- allow toggling animate on/off with `evaluate` and `stop evaluate` buttons?
- ???

**Screenshots**
See it here: https://www.loom.com/share/5e528da9f48a44339d26fc91f34a6c63

![Screen Shot 2022-07-29 at 4 26 12 PM](https://user-images.githubusercontent.com/8475488/181860084-36466c47-f29c-449f-a75d-d2688ed8cd17.png)

**Comment by BrooklinJazz** [comment]
Oooh! I knew they kept animating, but that's a great point. It would be awesome to create a custom Animation smart cell or something that would provide users control over animations. 🤔 It's annoying that if someone evaluates all with the `ea` animations, all start playing.

This would make a great project for the weekly hack-a-thing or something I'll do on my own time - it could make a great open source project.
