### ISSUE TITLE
Livebook server not starting [Windows] (not WSL2)

### ISSUE THREAD

**Issue by Akteivias** [DockYard-Academy/beta_curriculum#212]
**Describe the issue**
When `livebook server start.livemd` is called Livebook could not start distributed node. 

Note: This is a Livebook known issue ([196](https://github.com/livebook-dev/livebook/issues/196), [194](https://github.com/livebook-dev/livebook/issues/194), [1042](https://github.com/livebook-dev/livebook/issues/1042)) that happens when some erlang files don't show a dialog for its firewall approval on the first Livebook execution after being installed.

As there is no windows version for asdf, my tools setup was done with [Chocolately ](https://community.chocolatey.org/packages/Elixir) and [NVM](https://github.com/coreybutler/nvm-windows).

**Solution proposal**
Add a Windows-specific solution for this behavior on documentation:
- Before calling Livebook, execute on terminal `iex --sname test`
- On appearing Windows firewall dialog, approve permission for `epmd.exe`
- Both `erl.exe` and `epmd.exe` should appear on firewall-allowed apps

**Environment** 
OS: Windows 11 
Erlang/OTP: 24 [erts-12.0]
Elixir 1.13.3 (compiled with Erlang/OTP 22)

**Reproduction Steps (If Applicable)**
1. Oen command line (CMD/PowerShell)
2. From the `beta_curriculum` project folder execute `livebook server start.livemd`

**Expected behavior**
Curriculum Liveboook server should start and load the curriculum.

**Actual behavior**
Curriculum Liveboook is not started.

**Screenshots/Logs**
```
C:\Users\Oct\Elixir\DockYard-Academy\beta_curriculum>livebook server start.livemd

ERROR!!! [Livebook] Could not start distributed node: {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}}, {:child, :undefined, :net_sup_dynamic, {:erl_distribution, :start_link, [[:livebook_7isuoce5, :shortnames, 15000], false, :net_sup_dynamic]}, :permanent, false, 1000, :supervisor, [:erl_distribution]}}
```

**Comment by BrooklinJazz** [comment]
Hi @Octavio-GH! Would you be interested in making a PR to add this to the [Troubleshooting](https://github.com/DockYard-Academy/beta_curriculum#troubleshooting) section of the README?

**Comment by Octavio-GH** [comment]
Sure, on it. 

Is Chocolately(Elixir/Erlang) / NVM(Node.js) a good toolset for Windows, or will it be deprecated to use WSL2 in this project? A standardized setup for Windows could be helpful.

**Comment by BrooklinJazz** [comment]
I've been thinking about this but haven't come to a solid conclusion yet. I need more feedback from other Windows users not using WSL2 (I use WSL2).

Personally, I think that WSL2 is the most reliable Windows setup for Elixir. It's also less headache when setting up prerequisites like Postgres, Phoenix, etc. It's certainly the recommended setup for students.

However, I'm worried about alienating Windows users or creating a large barrier to entry in front of new developers, so I'm hesitant to require it. If it's not too much effort to support folks on Windows w/Chocolately then I'd like to where possible.

That said, I'd love to create a standard setup on Windows guide that walks through setting up the course and WSL2. In general, we could use some better setup guides for each OS.
