### ISSUE TITLE
Write Operating System Specific Setup Guides

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#221]
## Update Quickstart Guide

The current quickstart guide doesn't contain several important steps such as:
- How to setup ASDF (which I'm not convinced we should use 🤔) Maybe it would be easier to include a link to instructions for installing Elixir and Erlang directly. https://elixir-lang.org/install.html
- Adding ~/.mix/scripts to PATH

## Create OS-Specific WIKI Entries.

Having a more in-depth step-by-step setup guide (with pictures and links + debugging steps) for each OS would be incredibly helpful.

- [ ] Write MacOS Guide @petros 
- [ ] Write Windows Guide @crismxiex 
- [ ] Write Windows + WSL Guide
- [ ] Write Ubuntu GUide

**Comment by BrooklinJazz** [comment]
If anyone has not set up the curriculum, I'd be happy to sit down to set it up with them and document the process from scratch.

**Comment by petros** [comment]
I am thinking I might be able to write the macOS instructions?

**Comment by BrooklinJazz** [comment]
That would be fantastic! Do you need me to provide any GitHub permissions to contribute Wiki Entries?

**Comment by BrooklinJazz** [comment]
If possible, I'd like to include pre-requisite setup in there as well (Postgres, asdf, etc)

**Comment by crismxiex** [comment]
I can write the windows setup guide

**Comment by BrooklinJazz** [comment]
That would be great! Are you planning to use WSL or no? I think it would be great to have a guide for both.

**Comment by crismxiex** [comment]
Im not using WSL at the moment but i could write for both.

**Comment by BrooklinJazz** [comment]
That would be fantastic! Let me know if I can help

**Comment by BrooklinJazz** [comment]
This is the draft for Windows by @crismxiex

![image](https://user-images.githubusercontent.com/14877564/183144459-3716035d-167e-44ea-ba90-7c31d990ec92.png)

**Comment by BrooklinJazz** [comment]
Feedback:
- Remove Chocolatey from instructions
- Add **How To Run The Curriculum** step with images of how to navigate Livebook UI to open DockYard Academy curriculum.
- Remove the Congratulations language and keep it instructive.
- Capitalize Livebook and Windows.

**Comment by petros** [comment]
If I may add:
- stick to a concistent way of capitilizing Elixir. I would go with "Elixir" instead of "elixir".

**Comment by petros** [comment]
> How to setup ASDF (which I'm not convinced we should use 🤔) Maybe it would be easier to include a link to instructions for installing Elixir and Erlang directly. https://elixir-lang.org/install.html

My suggestion is to mention both options:
1. https://elixir-lang.org/install.html#macos 
2. and [asdf](https://asdf-vm.com)

With (1) we cover most folks new to programming. They haven't reached the point where they need multiple versions of the same platform/language. And they are looking for the simplest, easiest and fastest way to get up and running. That's Homebrew on macOS hands down.

With (2) we cover a smaller pecentage of folks that may be coming from other languages and they may not want to mess their installations. `asdf` is compatible with other runtime version managers as well, so there's no risk of messing with existing installations, like `rbenv` or `nvm` for example. We can point them to the installation guides. Or we can extract a quick guide of our own from their guides, distilled to macOS. That may mean more maintainance in the future as a downside for us though.

**Comment by BrooklinJazz** [comment]
I think I'm OK with mentioning both. However, these guides are more for new devs, so the more straightforward, the better. I'd like to specify that 1 (https://elixir-lang.org/install.html#macos) is the recommended option.

**Comment by mvkvc** [comment]
I can do the Ubuntu one as well as any other outstanding (Windows w/ WSL looks unclaimed rn, assuming Ubuntu for that also). Will mention `asdf` as you say above but make clear that the recommended is the install from the website.

**Comment by BrooklinJazz** [comment]
@mvkvc Wahoo! 🥳🥳🥳🥳 That would be awesome. @crismxiex mentioned he could do WSL but I'm not sure how full his plate is right now.

**Comment by crismxiex** [comment]
Go ahead thanks for the help! @mvkvc Ill try to have the pr for the windows guide today

**Comment by mvkvc** [comment]
I wrote instructions for them all, PR is here #269. @crismxiex no worries and feel free to edit/add to it.

**Comment by BrooklinJazz** [comment]
All guides have been created. Closing this issue.

**Comment by petros** [comment]
Thank you so much. Really sorry I didn't came through. I spend most of my time these days vacationing and taking part in Exercism's exhort. I still want to help here, as soon as possible 😄 🙇

**Comment by BrooklinJazz** [comment]
Please don't feel any stress over it! Any time you have to help out is greatly appreciated 🙏
