### ISSUE TITLE
Create Script to find broken links

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#222]
Create a script to read through the `reading` and `exercise` folders.

- Ensure all internal  links in the reading folder are valid: `[Reading Example](./reading_example.livemd)` instead of `[Reading Example](./reading/reading_example.livemd)`
- Ensure all internal links are in the exercises folder are valid: `[Exercise Example](./exercise_example.livemd)` instead of `[Exercise Example](./exercises/reading_example.livemd)`
- Ensure there are no empty links i.e. `[Named Link Without URL]()`

The `"Teacher-only editors are hidden""` test provides a good template for how to do this:

```elixir
  test "Teacher-only editors are hidden" do
    exercises = fetch_livebooks("../exercises/")
    reading = fetch_livebooks("../reading/")

    assert any_show_editors?(exercises ++ reading) == false
  end

  defp any_show_editors?(livebooks) do
    livebooks
    |> Stream.map(fn file ->
      File.stream!(file, [], :line)
      |> Enum.any?(&String.contains?(&1, "TestedCell.Control.show_editors()"))
    end)
    |> Enum.any?()
  end

  defp fetch_livebooks(path) do
    File.ls!(path)
    |> Stream.filter(&String.ends_with?(&1, ".livemd"))
    |> Enum.map(&(path <> &1))
  end
end

```

We can use regular expressions to check for issues such as:
- reading links: `\]\(reading\/\w+\)`
- reading links: `\]\(exercises\/\w+\)`
- empty links: `\]\(\)`

**Comment by Mraiih** [comment]
I'd be glad to take this one too 😄
