### ISSUE TITLE
Add Mermaid Diagrams to Visualize Different Supervisor Restarting Strategies

### ISSUE THREAD

**Issue by kianmeng** [DockYard-Academy/beta_curriculum#288]
We should take inspiration from these diagrams found in https://www.erlang.org/doc/design_principles/sup_princ.html to visualize different restarting strategies.

**Comment by BrooklinJazz** [comment]
Hard agree! We should do this at the same time as #141

**Comment by AdrianPaulCarrieres** [comment]
I'm not sure Mermaid can add the arrows under the diagrams like in Erlang's docs for the termination/restart order of the process

**Comment by BrooklinJazz** [comment]
We can change the direction of mermaid diagrams using `TB` for top to bottom. We can also style them similarly to the example diagram with the border and background color.

Here's an example:

```mermaid
flowchart TB
S[Supervisor]
S -->P1((P1))
S --> P2((P2))
S --> P3((P3))
style P1 fill:lightcoral,stroke:lightgreen,stroke-width: 4px
style P2 stroke-width: 4px
style P3 stroke-width: 4px
style S stroke-width: 4px

```
