### ISSUE TITLE
All references to documentation functions should be links instead of code notes.

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#290]
To make research easier for students, we should prefer links such as [Enum.reduce/2](https://hexdocs.pm/elixir/Enum.html#reduce/2) instead of `Enum.reduce/2`.

**Comment by aayushmau5** [comment]
I'm wondering how to automate this process :thinking: 

Is this issue something that requires manually going through each lesson and adding those links?

**Comment by BrooklinJazz** [comment]
I've written a script, it will be part of my content review PR 😄
