### ISSUE TITLE
Add .node-version file or add .node-version to .gitignore?

### ISSUE THREAD

**Issue by rjfranco** [DockYard-Academy/beta_curriculum#293]
**Describe the issue**
If using tooling for node version like nodenv, which relies on a `.node-version` file, would be nice if this file was either already present – or intentionally ignored to avoid commits / git diff

**Proposed solution**
I think it may actually be preferable to add this to .gitignore since the preferred tooling in the guide seems to be asdf, to keep things consistent

(I'm happy to make a PR, just wasn't sure which direction is preferable, if any)

**Comment by BrooklinJazz** [comment]
I think adding it to the .gitignore sounds good!

**Comment by BrooklinJazz** [comment]
A PR would be highly appreciated :D

**Comment by BrooklinJazz** [comment]
@rjfranco would you be interested in making a PR? If not all good I'm going to leave this issue open since it's a good first issue for anyone wanting to learn how to contribute.

**Comment by zorn** [comment]
Can I ask a related question: What do we use node for?

**Comment by BrooklinJazz** [comment]
That's a really good point. I think there might not be any point to it at all! We should remove it.
