### ISSUE TITLE
Livebook Elixir version requirement conflicts with our current `.tool-versions`.

### ISSUE THREAD

**Issue by zorn** [DockYard-Academy/beta_curriculum#307]
I'm experiencing a conflict in that the current wiki page for [Beta Tester Guide & Contributor Setup](https://github.com/DockYard-Academy/beta_curriculum/wiki/Beta-Tester-Guide-&-Contributor-Setup#install-livebook) asks one to run:

```
mix escript.install github livebook-dev/livebook
```

But when I do I see the output:

```
** (Mix) You're trying to run :livebook on Elixir v1.13.4 but it has declared in its mix.exs file it supports only Elixir ~> 1.14
```

I believe this requirement landed in livebook here: 

https://github.com/livebook-dev/livebook/pull/1380

This leads me to understand that the `mix escript.install github livebook-dev/livebook` command installs the version of livebook on main? 🤷‍♂️ 

Maybe we should recommend a specific version? OR we'll need to consider updating our own `.tool-versions` file (and other docs) to use (require) Elixir 1.14.

**Comment by BrooklinJazz** [comment]
You're right! I believe we changed this in the readme but not the contributor guide. I believe the command is:

```
mix escript.install hex livebook
```

I'll update the contributor guide.

**Comment by BrooklinJazz** [comment]
We should also update our .tool-version file.

**Comment by BrooklinJazz** [comment]
Can you confirm the command above fixes the issue?

**Comment by BrooklinJazz** [comment]
And yes, you are correct. This issue stems that the latest livebook release uses version 1.13.4 and does not work with elixir `1.14`.

However, the `main` branch of livebook installed using the previous command `mix escript.install github livebook-dev/livebook
` only works with elixir 1.14.

We used to need the main branch for not-yet-released features. However, that changed (once they were released) and now we prefer the more stable release. That might be a wrong choice though 🤔

**Comment by zorn** [comment]
> You're right! I believe we changed this in the readme but not the contributor guide. I believe the command is:
> 
> ```
> mix escript.install hex livebook
> ```
> 
> I'll update the contributor guide.

This looks good for me. Thanks for the guidance.

**Comment by zorn** [comment]
Closing this as the `.tool-versions` concern is being recorded via #308
