### ISSUE TITLE
Write a test to ensure .tool-versions stay up to date

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#308]
I'm not sure if this is a good idea or not, but it's kind of tedious and bug prone to manually update our tool-versions.

I'm open to ideas here, but perhaps a test + script to automate this would be a good idea.

**Comment by zorn** [comment]
There is an open issue to get support for this kind of thing from dependabot. 

https://github.com/dependabot/dependabot-core/issues/1033

In that thread, there is a link to someone's GitHub Action that might help.

**Comment by zorn** [comment]
That said, my gut reaction is that any significant updates to `.tool-versions`, particularly for this project, will likely have to accompany other sanity checks to verify the new version of Elixir does not break things **and** is properly referenced in wiki docs and other things.

I'm not sure how automated it could really be. 🤷‍♂️

**Comment by BrooklinJazz** [comment]
Thank you for linking to the workflow. I agree I don't think we can truly automate resolving the issue. However, it would be great to automate catching this issue.

That said, I realized this is only a concern when using the main branch because they could suddenly update or change the required Elixir version. I'm tentatively closing this issue because I don't think it's a problem if we use a stable version.

However, if we ever have a reason to recommend the main branch we should re-open this.
