### ISSUE TITLE
missing "s" in the script label:documentation

### ISSUE THREAD

**Issue by bpsundar** [DockYard-Academy/beta_curriculum#310]
A typo to be corrected
PATH=$PATH:~/.mix/escripts

![image](https://user-images.githubusercontent.com/42065587/188307329-0dde4038-b399-4cfd-8c72-4612f0d71ccd.png)

**Comment by BrooklinJazz** [comment]
Good catch! Are you able to make a PR to fix this? I'm happy to pair-program with you or walk you through the process if you have time

**Comment by bpsundar** [comment]
yes, I will be happy to learn to do that.

**Comment by BrooklinJazz** [comment]
The process is:
1. create a [Fork](https://github.com/DockYard-Academy/beta_curriculum/fork) of the curriculum.
2. clone the fork onto your computer
3. create the change (using livebook or your code editor)
4. stage the change `git add .` from the project folder
5. commit the change `git commit -m "add s to escript typo"`
6. push the change `git push`
7. create a pull request from your fork to the main branch of the curriculum repository.
8. Review the file changes to ensure there are no issues, and ensure that all tests pass (you may need me to approve the test workflow first)

Do you have any questions? I'd be happy to set up a time to video chat if you prefer?

**Comment by bpsundar** [comment]
done
