### ISSUE TITLE
URL text not converted to HTML link

### ISSUE THREAD

**Issue by kianmeng** [DockYard-Academy/beta_curriculum#331]
**Describe the issue**
Second URL text not converted to HTML link

**Reproduction Steps (If Applicable)**
1. Go to 'Week 6:Ecto Associations'
2. Click on 'Portfolio: Blog search'
3. Scroll down to 'Blog Controller'

**Expected behavior**
Expect a URL text converted to HTML link.

**Screenshots**
![image](https://user-images.githubusercontent.com/134518/189946151-a250625b-183c-4235-9816-120ecfd32815.png)

**Comment by zorn** [comment]
Thanks for the bug report. PR posted! 👍

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:
