### ISSUE TITLE
Avoid suggesting non-guard function names with `is_` prefix in lessons/challenges. (ie: Anagrams).

### ISSUE THREAD

**Issue by zorn** [DockYard-Academy/beta_curriculum#332]
In the Anagram lesson last night, we had students implement a predefined function named `is_anagram?/2`.

Technically, according to the [naming guidelines](https://hexdocs.pm/elixir/naming-conventions.html#is_-prefix-is_foo) we should not use the `is_` prefix unless that function was written as an allowable guard function.

<img width="854" alt="Screen Shot 2022-09-13 at 4 27 57 PM" src="https://user-images.githubusercontent.com/52168/190003490-4cd80920-11e5-448d-b35d-83169a01f819.png">

I would suggest we refactor the lesson to instead use the name of `anagram?/2`.

**Comment by BrooklinJazz** [comment]
Great catch - this is more idiomatic.
