### ISSUE TITLE
NEWBIE - Fun Formulas - Unable to resolve the tests even with the suggested solutions

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#343]
I am attempting to go through the Fun Formulas lesson, but I always get error messages. Either I am doing something wrong (probably newbie behavior on my part), or something else is going on. I am using the "suggested solutions" to troubleshoot, but no change of outcome. Just different error messages. I attach screenshots.

1. Go to 'Fun Formulas'
2. Click on each test and type the answer replacing "nil" with the suggested solution
3. Click evaluate
4. See error _"invalid character "l" after number 100."_

I understand I should get a green message confirming that the test has been passed

I appreciate you checking on this...

![image](https://user-images.githubusercontent.com/113518695/190715719-fde940e0-bfcc-46a6-9dbc-680bb5907264.png)

**Comment by BrooklinJazz** [comment]
You aren't doing anything wrong! I believe this is a known livebook bug: https://github.com/livebook-dev/livebook/issues/1399

I'm in the middle of making a PR that will move away from using the Tested Cell and resolve this issue. Thank you for the issue report!

**Comment by BigSpaces** [comment]
Good to know, Brooklin. Thank you for your response and for following up on resolving this issue. I am very much looking forward to our chat on Monday! (Jon Valdivia, friend of Angel Imaz)

**Comment by BrooklinJazz** [comment]
Same here! Looking forward to meeting you Jon :D

Resolved by #346
