### ISSUE TITLE
Suggestion: Create a "Way of Teaching" document.

### ISSUE THREAD

**Issue by zorn** [DockYard-Academy/beta_curriculum#348]
I once worked for a company called Big Nerd Ranch. I was an instructor, and we would do week-long on-site workshops teaching Swift and the iOS frameworks.

There were over a dozen instructors, and to help make sure we each delivered high-quality and consistent experiences, we did lots of internal teaching; a teach the teachers to teach sort of thing.

One asset of this effort was an internal book (we wrote lots of books) that explained the "Way of Teaching". In this book, we tried to capture our core values, how we taught and why we thought this process was successful. We also captured lots of little details about the week, your body language and attitude, being approachable, dealing with struggling students, dealing with disruptive students, and so on.

I can not share the actual book PDF, but I can share the types of questions I would expect a document like this to answer. By writing such a document, you (Brooklin) can better understand what this academy will be about and how it will be delivered. 

Additionally, if the academy is ever to scale, you'll need to be able to teach new teachers.

**Academy Mission Statement**

Why are we here? 

**Academy Core Values**

When evaluating what we want to accomplish and how we will get there, what considerations impact these decisions? What are our values? How are our values expressed in day-to-day processes?

**Lecture Schedule and Format**

How do we teach? What does a lecture look like? a full day? a full week? a full month? a full cohort (3 months)?

How do we know if we are successful?

How do we encourage student questions? Dealing with out of scope questions. Dealing with smart-ass students.

What are the properties of a good coding exercise?

**Body, Attitude, Voice**

How should an instructor behave? How do they gain trust and confidence from the students? Why is trust and confidence from the students important? Why is empathy for the student important?

The importance of the first day. Setting expectations.

Explain to the students that they will be confused and frustrated at times. This is expected and normal.

Be clear and repeat the schedule, breaks (short and longer), next lesson, etc.

You are not selling the technology. Students will appreciate your honesty when explaining things you love and things you love less. 

**Practice and Improvement**

Record yourself teaching, and watch for ticks and other distractions.

Teaching club. Do a lesson for other teachers. Have them cirque your delivery. 

How to deliver and accept critical feedback.

Setting up your computer for an ideal screen-sharing environment.

Camera / Lighting for video conferences.

How to take screenshots for documentation.

The challenges of online-only instruction. How to tackle these issues head-on.

You will typically discover improvement opportunities in the content directly after teaching it. This could be typos or larger concerns. It is vital to capture these right away before you forget them.

Finding technical reviewers for content.

**Other Questions**

How do we handle students' missing days? Longer absences?

What happens after the course?

**Comment by BrooklinJazz** [comment]
This is a wonderful suggestion. We've been thinking internally about how to train other teachers and this would be excellent.

I'd like to create this resource once we're looking to create more teachers (after the first cohort) but will leave this issue open to aggregate related resources and server as a reminder for when I am ready to put my current thoughts into a document.

**Comment by zorn** [comment]
Even as a solo course designer/teacher, I think you'd benefit from self-documenting your mission, values, goals, and techniques. Think of it like a business plan. Rarely are these plans ever perfect on their first pass, but as the business faces challenges and needs to evolve, it serves as a guidepost to document your thinking and expectations of the time.

That said, your time is your own. This is not something I can write for you. Hope the notes are helpful to you in the future. 💜

**Comment by BrooklinJazz** [comment]
We're creating this document internally. Thank you for the excellent suggestion!
