### ISSUE TITLE
Undefined error hero/0 in 'Structs' exercise

### ISSUE THREAD

**Issue by Billboz** [DockYard-Academy/beta_curriculum#356]
In the 'Structs' livebook, I am getting this error -
```
10: undefined function hero/0 (expected Hero to define such a function or for it to be imported, but none are available)
```

I am thinking that the following line defines hero/0 -
```
defstruct [:name, :catchphrase, :secret_identity]
```

Here is the code -
```
defmodule Hero do
  defstruct [:name, :catchphrase, :secret_identity]
  #@enforce_keys [:name]

  #def new(name) when is_binary(name) do
  #  {:ok, %Hero{name: name}}
  #end

  def reveal(name) do
    "I am secretly #{hero.secret_identity}"
  end

  def introduce(greeting, name) do
    "#{greeting} I am #{hero.name}"
  end
end
```

The instructions say to use -
```
"#{greeting} I am #{hero.name}"
```

This does not compile and I get this error -
```
(UndefinedFunctionError) function Hero.name/0 is undefined or private
    Hero.name()
```

It will compile if I capitalize the hero in both of the #{hero.secret_identity / .name} but when I do this the exercise two down fails with the same error as above.

This is the command -
```
Hero.introduce("Hi!", spider_man)
```

Where spider_man is matched to -
```
%Hero{
  name: "Spiderman",
  catchphrase: "Friendly neighborhood Spiderman",
  secret_identity: "Peter Parker"
}
```

**Expected behavior**
Honestly, I am a noob and Brook asked that I submit a ticket.  He mentioned the issue might be in the testing but he was pressed for time so he could not elaborate.

**Comment by BrooklinJazz** [comment]
I believe we resolved this issue. The parameter was `name` but the argument was a hero struct.
