### ISSUE TITLE
Toggle lines (commenting) not working in Livebook + Windows 10 + Brave

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#377]
I cannot toggle comments in Livebook using Ctrl + / . 

I use Brave in Windows 10.

**Comment by BrooklinJazz** [comment]
Hmmm. Did you get any warning when you tried it, or does it simply not work? I think sometimes you have to start the runtime before you can run commands.

You can look at the keybindings section on Livebook to see if it's the correct keybinding or not.

**Comment by BrooklinJazz** [comment]
We resolved this issue. It was caused due to having a Spanish keyboard without the `/` symbol. @BigSpaces can you post here what the correct keybinding was so we can document the solution?

**Comment by BigSpaces** [comment]
Hello Brook,

The solution provided was Ctrl + K + C. Mind you, it is the first time that a documented key shortcut does not work because of the language of the keyboard. They tend to be universally transferrable (or that has been my experience up until now)

Thank you

**Comment by BrooklinJazz** [comment]
I think we should raise an issue on https://github.com/livebook-dev/livebook/issues

I think the division operator `/` on the number pad of your keyboard should still trigger the command (but I could be wrong).

**Comment by BrooklinJazz** [comment]
I've started a discussion: https://github.com/livebook-dev/livebook/discussions/1436
