### ISSUE TITLE
Feedback on "Match Operator"

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#379]
Hello again Brook,

A spontaneous impression as a newbie reading through the material in the "Match Operator" page.

I find that pattern matching is a mind-bending concept in its own right. For a new person reading who does not understand what a tuple is (or a list, or a map), to exemplify the match operator and pattern matching with those data types may lead to unnecessary headache.

I feel like it using apples and oranges to do math, without knowing what an apple is or an orange is (sorry I am doing a reductio ad absurdum to try and make my point).

See you in a bit

**Comment by BrooklinJazz** [comment]
I completely agree. I moved the pattern matching with collections section out of the Match Operator Lesson so that it will be in its own reading material after we cover collections.
