### ISSUE TITLE
Feedback on pattern matching lists

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#387]
Hello Brook,

I hope I am not overwhelming the inbox with my particulars. This is just me sharing my experience with the intention of raising awareness on potential roadblocks to future students. I am also starting to see that my mind gets things through storytelling, while yours is way more structured and "engineer-like", which transfers into the writings, of course. 

Thank God now I am using Livebook mess around and translate your concepts to my particular inner language. That said, here is some feedback on the section pattern matching lists.

![image](https://user-images.githubusercontent.com/113518695/192136037-5345ef36-bd43-4dbd-8648-b39d9bd714d2.png)

Right there in those three sentences you mention pattern matching and maps. I am so new to Elixir that "pattern matching" and "maps" are fuzzy and unstable concepts still. Maybe that won't be the case for the cohort, but I feel I am asked to rock-climb while holding on unstable grips, so the rest of the explanation free-falls for me.

This may be not so much an "issue" but an observation. Each lesson demands a very firm grip on the previous concepts. But of course, when the cohort starts, there will be 4 additional hours of drillings.

And we continue!

**Comment by BigSpaces** [comment]
Oh, I forgot to clarify... I actually made great progress in the lesson. I feel I got it and I am internalising the concepts :)
[head-tails.zip](https://github.com/DockYard-Academy/beta_curriculum/files/9640493/head-tails.zip)

**Comment by BrooklinJazz** [comment]
Keep the suggestions coming! This is really helpful for me (and everyone who benefits from curriculum improvements)

My plate is full so it might take me time to circle back to your suggestions, but I don't want that to seem like I'm ever ignoring them. Thank you for sharing your thoughts 🙏

I'm not sure if I addressed this fully in my last content review, but I will review the latest content and double check.

**Comment by BigSpaces** [comment]
Sounds good. I will keep the suggestions coming, and worry not about not responding. I know you are busy. If there is anything in particular I need help with, I will raise it on class or through Discord. Thank you!
