### ISSUE TITLE
Tuples and Pattern Matching

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#396]
Hello Brook,

I don't know if this is a bug, typo, or if I am missing something... In the Pattern Matching section of the tuples module, there is an empty code cell. Are we supposed to fill it and run a test of some sort? It is not clear to me by reading the text above the code cell.

![image](https://user-images.githubusercontent.com/113518695/192203562-15475965-49df-46dc-a3f5-64f78f38fd3d.png)

Keeping on...

**Comment by BrooklinJazz** [comment]
Good catch. Updating the content in my next PR
