### ISSUE TITLE
Defined Functions

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#399]
Hello Brook,

I do not know if this is by design, but unless I have missed a step, we go from the "functions" module to the "modules" module without having introduced named functions.

It seems that how to define modules and how to define functions are concepts that are introduced simultaneously, while in the "functions" module there is only "anonymous functions" at work?

Again, this may be by design, but reading at the beginning of the module it seems that knowing how to define functions should be known at this point:

![image](https://user-images.githubusercontent.com/113518695/192290906-c4a3c705-ca7f-460d-8d27-ed9474081144.png)

Although a bit later in the text, it is explained for the first time how to declare a named function:

![image](https://user-images.githubusercontent.com/113518695/192291130-d6e20f8b-3c8b-4ffb-9e0d-c53d94549adf.png)

Would it make sense to separate these three topics in three modules?
1. Anonymous Functions
2. Named Functions
3. Modules

Hope it helps. 

Jon

**Comment by BrooklinJazz** [comment]
Named functions must always be in a module so I'm not sure how to split them 🤔 maybe there's an approach but they seem like they need to be covered at the same time.

**Comment by BrooklinJazz** [comment]
I'm going to close this issue as I don't think it's actionable, but please re-open it if you disagree!
