### ISSUE TITLE
Track Student Progress

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#40]
Add a mechanism to track student progress and completion of exercises.

**Comment by auranykh** [comment]
I think we had discussed this a little bit before, but some ideas would be to tie completion to "Your Turn" challenges within the readings and the exercises. Once these are complete and successfully past some unit test, the exercise will mark itself complete. 

Alternatively, adding a simple check box to each challenge would be a very simple and rudimentary way to track progress, but would rely on the students checking the boxes themselves.

**Comment by w0rd-driven** [comment]
What about leveraging ETS? The only downside is you lose state whenever Livebook terminates which is a bit of a problem. An example I've seen is in the SpiderMan crawler's [Utils module](https://github.com/feng19/spider_man/blob/master/lib/spider_man/utils.ex) in the `dump_ets2file` and `setup_ets_from_file!` functions respectively. The biggest problem I see with the approach is to persist before the process is killed (or on every save which seems like overkill) and to read the various table files into memory.

An alternative approach could be SQLite or a database but that may be a steeper dependency. Whatever the storage mechanism, this could also be leveraged for the various `Util.form()` calls to persist those values as well.

By detecting the `Your Turn` sections, you could also list things like list x/y complete as fractions and percentages or do things like navigate to the last completed section. That would seem useful as a custom widget on each notebook either as the very first section or if it could hover in perhaps the top right of the page. Hover could be problematic when the ToC is visible though.

**Comment by BrooklinJazz** [comment]
Apologies for the terribly late response. I've changed my email settings so that I should see these better in the future.

ETS is an implementation detail, and in-memory persistence so we'd likely need some longer-term system like the file system. It may play a role in the solution though.

The challenge is: How do we track student progress? what should we track? I'm going to close this issue for now, because I think it will become more clear how to solve it when the testing system is more finalized. Students could also simply submit their github repos for teacher review, the teacher then reviews their projects ensure they are complete 🤔
