### ISSUE TITLE
Using a piped function within another function

### ISSUE THREAD

**Issue by tindrew** [DockYard-Academy/beta_curriculum#405]
**Describe the issue**
Inside the Pipe Operator section: 
There doesn't seem to be an example of using a piped function within another function in the curriculum. For example: 

the hint shows for the example: 

```
add = fn int1, int2 -> int1 + int2 end
subtract = fn int1, int2 -> int1 - int2 end
multiply = fn int1, int2 -> int1 * int2 end

10
|> add.(2)
|> multiply.(2)
|> subtract.(4)
```
which can be confusing because we have been writing functions up to this point now. I think it would be helpful to at least give a small example of how a pipe is added inside a function. Example: 

```
add = fn int1, int2 -> int1 + int2 end
subtract = fn int1, int2 -> int1 - int2 end
multiply = fn int1, int2 -> int1 * int2 end

all_together_now = fn -> 10
  |> add.(2)
  |> multiply.(2)
  |> subtract.(4)
end

#calling the function
all_together_now.()
```
You could use a smaller example without giving a full solution of course, just so people could see how to actually use pipes within a function.
Hope that helps.

**Comment by BrooklinJazz** [comment]
I'm not sure how adding Pipes within a function adds more clarity. Pipe operators are a separate concept from writing code inside the body of a function, and it doesn't change how we use them, whether they are inside a function or not.

I will close this issue for now but am still open to further discussion if you disagree.

**Comment by tindrew** [comment]
Maybe it's my lack of understanding, but this bit of code
10
|> add.(2)
|> multiply.(2)
|> subtract.(4)

Is confusing on it's own. There's the number 10, but no indication that anything is being done to it. Am I just missing something, because I thought that pipes are away to organize/use functions within a function.

**Comment by BrooklinJazz** [comment]
A pipe takes any value and passes it as the first argument to a function. It is a way of calling a series of functions.

```mermaid
flowchart
i1[input 10]
f1[add 2]
o1[output 12]
f2[multiply 2]
o2[output 24]
f3[subtract 4]
o3[output 20]

i1 --> f1 --> o1 -->
f2 --> o2 -->
f3 --> o3 
```

Therefore it's common to start with an elixir term such as `10` and then pipe it into the first function in a series of piped functions.

So the following code evaluates like so:

Step 1:

```elixir
10
|> add.(2)
|> multiply.(2)
|> subtract.(4)
```

Step 2

```elixir
12
|> multiply.(2)
|> subtract.(4)
```

Step 3

```elixir
24
|> subtract.(4)
```

Step 4

```elixir
20
```

**Comment by tindrew** [comment]
Ahhh ok that makes sense now. Thank you 😊

**Comment by BrooklinJazz** [comment]
It does help us organize functions, as the alternative would be the following without the pipe operator:

```elixir
|subtract.(multiply.(add.(10, 2), 2), 4)
```

However, the **within a function** part is optional, not mandatory. Using the pipe operator within a function is the same as writing any code. There is no change, we simply put the same code in the body of the function.

**Comment by BrooklinJazz** [comment]
I think I should add this to the reading material. I'm going to reopen this issue to remind myself to address this.

**Comment by BrooklinJazz** [comment]
Closing this issue because we already have the example I thought I needed to add in:
![image](https://user-images.githubusercontent.com/14877564/194736088-87f9be97-92f5-4e0d-ac22-379736968f30.png)
