### ISSUE TITLE
A suggestion on making parameters explicit for students

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#408]
Hello Brook,

It took me a few minutes to understand the difference between Enum.reduce/2 and Enum.reduce/3:

- I had to clear away my confusion that `fn element, accumulator` is actually ONE parameter, not two (newbie brain). So at first I thought that Enum.reduce/3 was passing four parameters. Still getting used to the idea that we can pass entire functions as parameters in Elixir.

- I had to infer the order of the parameters to fully grasp where the first value of the accummulator is placed.

- Since both declarations are very similar, it obfuscated the understanding a bit, though it was good practice to find the nuances and understand their meaning.

So I made these notes, which could be useful to other students when presenting reduce/2 and reduce/3, for the sake of clarity.

![image](https://user-images.githubusercontent.com/113518695/192739605-d76f1e43-a63e-4a61-b3de-d14a0f3cc807.png)

Hope it helps!

**Comment by BrooklinJazz** [comment]
I think it's important to stress the difference. However, there is a section dedicated to reduce/2 vs reduce/3, so I'm going to close this issue.
