### ISSUE TITLE
Ordering confusion...

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#409]
Hello Brook,

I found it confusing to have Enum.map explained again just after the additional functions are introduced. In my mind, we had just worked through map, filter and reduce, and now the next function to tackle was Enum.all . Instead, we go back to Enum.map and delve deeper into it.

Would it make sense to go all the way with Enum.map first, and then work through all the functions sequentially?

![image](https://user-images.githubusercontent.com/113518695/192740664-f012a0e9-59ee-4451-88f2-f89000a3a128.png)

**Comment by BigSpaces** [comment]
Actually... now I see that you also delve deep into reduce/2 reduce/3 , filter, and all the rest after having introduced the additional functions.

Intuitively I think it could work better to delve deep into map from the get-go. I think it would provide a firm grasp of syntax and basic functioning first, to then move into other functions on Enum. 

Otherwise it could be too much to grasp: "enum + all the functions" on a first pass (too much info), as opposed to just Enum.map. One could get strong there, familiarise oneself with the syntax and the inner workings of Enum, and then start assimilating the rest of the functions building that first firm deep-dive into map.

My two cents!

**Comment by BrooklinJazz** [comment]
I think It could be beneficial to separate this lesson into map/filter/reduce in a single lesson, then the rest in another.

**Comment by BrooklinJazz** [comment]
I'm going to leave the content as is for now, however I may circle back to this in the future to separate the three main functions into a separate lesson.
