### ISSUE TITLE
Clarifying the explanation through re-structuring a bit

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#426]
Hello Brook,

Once again sharing the experience of going through the material and offering my two cents. When you start explaining how to ennumerate with strings, you introduce three methods: graphemes, codepoints, and split (screenshot below).

Then you jump directly into the second one, codepoints. I suggest unpacking them in order.

Also, you provide a header for graphemes as well as split, but do not provide a header in codepoints. My suggestion is to provide the header, so the student knows we are passed the initial explanation, and we are going to dive in each function at this point.

I found something confusing: You explain that a codepoint is an integer that represents a character, but the function does not return an integer. In fact, we have another method if we want to do that, which is to type ? before the character. My brain asks the question "if a codepoint is an integer, why does the function return strings?". Maybe providing a bit more context to the function and what is supposed to do will clarify this.

Finally, sometimes you refer to "codepoint" in one word, and others as "code point". I am happy to go through the document and standarise the word if you want me to. I can create a pull request once I it's done.

Thanks!

![image](https://user-images.githubusercontent.com/113518695/193216816-5fa22c87-109e-4d8a-a251-19f01169acfd.png)

**Comment by BrooklinJazz** [comment]
I can't find a consistent standard for code point so it's stick with adding the space and say **code point**.

![image](https://user-images.githubusercontent.com/14877564/193397189-e63dd7b2-1a4b-4d59-905f-2c809bf7a151.png)

I think I can better explain codepoints by using some characters that will separate into multiple codepoints similar to how the Elixir String documentation handles it.

![image](https://user-images.githubusercontent.com/14877564/193397245-759abda2-26f2-4651-8c77-7c11f5138c82.png)

I agree with all points raised. Will add this to my next content review.

**Comment by BrooklinJazz** [comment]
We no longer include String.codepoints in the reading material.
