### ISSUE TITLE
Comprehending comprehensions. Suggestion in odering.

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#427]
Hello Brook,

My experience going through the first part of this lesson was _"I must have missed something in my understanding of Enum.map, becasue I feel I already know how to do this, but this is a new lesson, so either I am missing something in the Enum.map material, or I am not getting something about comprehensions right now. I am trying to find the differences"._

And then, the bell rang:

![image](https://user-images.githubusercontent.com/113518695/193220232-d5f319f6-0f9a-4f96-a205-9a0e05ad0111.png)

May I suggest you start the lesson defining the territory by explaining that comprehensions are indeed syntax sugar? I intuit that will put the mind at ease, since my mind was trying to find the differences with Enum.map from the get go. Not a biggie, but it may be a nuance that helps.

Thanks!

**Comment by BrooklinJazz** [comment]
I realized I had not commented after 10 days! My apologies. I plan to circle back to this in review. I would also happily accept a pull request!

**Comment by BigSpaces** [comment]
Great! 

Did you receive a .livemd file I sent with my suggestions on how to order the material? This was a week ago more or less...

Happy to close this issue.

**Comment by BrooklinJazz** [comment]
I missed it! Let's keep the issue open until we make a PR to address the problem.

Let's take your suggested changes and implement them in a PR together! This makes for a great GitHub learning opportunity.

**Comment by BigSpaces** [comment]
Fantastic. Git is a dragon that I have not slayed yet, but it shall be defeated :)
