### ISSUE TITLE
Weighted Voting exercise: tally/1 

### ISSUE THREAD

**Issue by deltuh-vee** [DockYard-Academy/beta_curriculum#453]
**Describe the issue**
The WeightedVoting.tally/1 function has two different requirements. Do we want the output as a map or keyword list?

**Screenshots**
<img width="529" alt="image" src="https://user-images.githubusercontent.com/5289715/193977055-c93c8294-2467-4a59-8cba-f97d1907ce0f.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/5289715/193977114-69f83d13-313e-4813-aea7-ef61f6a59790.png">

**Comment by BrooklinJazz** [comment]
Thank you for bringing this up, I recently changed the exercise to build up a map but didn't change the documentation. Instead, I'm going to leave it as a bonus exercise
