### ISSUE TITLE
Incomplete "Factory" exercise

### ISSUE THREAD

**Issue by pascalwengerter** [DockYard-Academy/beta_curriculum#469]
**Describe the issue**
Seems like either an incomplete exercise or some sort of dev leftover? I don't find it linked anywhere from a quick cursory search

**Reproduction Steps (If Applicable)**
1. Go to https://github.com/pascalwengerter/beta_curriculum/blob/f1e936e6403d00c0239bd8378bbacf891afafffe/exercises/factory.livemd
2. See an seemingly incomplete exercise (It lacks the previous/next bottom section and has a `In order to understand more about` sentence leading nowhere)

**Expected behavior**
Not sure if only my expectation, but exercises on the `main` branch most likely should be in a working state? 🤗

**Comment by BrooklinJazz** [comment]
Interesting 🤔Definitely should be removed

**Comment by drueck** [comment]
I'd be happy to clean this one up unless you're already on it, @pascalwengerter?

**Comment by pascalwengerter** [comment]
> I'd be happy to clean this one up unless you're already on it, @pascalwengerter?

Please do go ahead, I'm frying different fish in this repo in the meantime 😉
