### ISSUE TITLE
Add Pull Request to Git Instructions

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#472]
![image](https://user-images.githubusercontent.com/14877564/194717693-8144e5a2-2f9d-4a60-b053-807133e9823b.png)

Students should start an exercise by ensuring they are on the `main` branch, then they should create a new branch for the exercise.

At the top of every lesson we should include instructions like so:

### Create an Exercise Branch
`git checkout -b exercise-name`

Then include PR instructions
`git add .`
`git commit -m "complete exercise-name"`
`git push -u origin exercise-name`
Then create a pull request. @mention your teacher to get their review.
Review the files changed to ensure they are correct.

**Comment by pascalwengerter** [comment]
I'd love to take care of this issue, and suggest I base it on #473 (which introduces re-running the git scripts which is necessary to update them anyways 😇 ) and wait for it to get merged

**Comment by BrooklinJazz** [comment]
I realized I think we should also include some instructions to checkout into main first before completing the exercise.
Let me know if you want to collaborate on what the instructions should look like exactly.
