### ISSUE TITLE
Course Outline

### ISSUE THREAD

**Issue by IciaCarroBarallobre** [DockYard-Academy/beta_curriculum#476]
**Describe the issue**
Some sections and subsections in the main index page are enumerated (With week X or X.Subsection) and others are not.

The index is so big now and it's difficult to search some sections sometimes :( maybe it's a good idea to split it

For ex:

Section
- Core Syntax
-  Built-In Tools
- ...
-----------
Section and subsections
- Core Syntax 
  - Course Tools
  - ... 
- Built-In Tools
  - Built-In Modules
  - ...
 - ...

**Comment by BrooklinJazz** [comment]
I agree!

The reason for the week vs non-week is I'm slowly reviewing the content and moving away from the week-by-week system.
It's not reasonable to expect every class to progress at exactly the same pace.

**Comment by BrooklinJazz** [comment]
I would happily accept a pull request that alters the course outline to use sections for each "day" as you suggested.
we'll just need to make sure that none of the project tasks break when we run `mix bc` from the command line.

For example, we auto-update the README based on start.livemd and I'm not sure how robust that script is.

**Comment by IciaCarroBarallobre** [comment]
So... Now, there aren't sorted by weeks, just by days?
Like...

Current Version
----

- Core Syntax
  - Course Tools
    - Reading
      - Command Line
      - Git
      - Livebook
      - Code Editors   
    - Exercises   
      - Command Line Family Tree
      - Livebook Recovery
      - GitHub Engineering Journal
      - GitHub Collab
  - Basics
    - Comments
      - Arithmetic
      - Strings
      - Booleans
      - Comparison Operators
      - Match Operator   
    - Exercises   
      - Fun Formulas
      - Card Counting
      - Habit Tracker
      - Mad Libs
      - Bonus: Guessing Games

Next version
----

- Core Syntax
  - Course Tools
    - Day 1: Command Line
      - Reading 
      - Exercises
        - Command Line Family Tree
    - Day 2: Git
      - Reading
      - Exercises
        - GitHub Engineering Journal
        - GitHub Collab
    - Day 3: Livebook
      - Reading
      - Exercises
        - Livebook Recovery
    - Day 4: Code Editors   
  - Basics
    -  Day 1: Comments
       -  Reading 
    - ...


What I proposed is to create an index in the overview with just the sections (Core Syntax) and subsections (Course Tools), for example, to easier access to concrete sections and subsections, but ignoring the subsubsection (Command Line, Git, etc). Because I think that only having the full index maybe complicate the search for a section or subsection.


Although,  if you have a new idea to solve this problem, I would be happy to change it following your idea :)

**Comment by BrooklinJazz** [comment]
I would like to remove all references to time "days"/"weeks" from the outline. This makes it easier to move course content around and removes the pressure for students to maintain a specific pace. For example, sometimes we'll have to repeat classes.

This also removes pressure from folks doing the curriculum at their own pace.

The sections Core Syntax, Built-In Tools, and Mix Projects all follow my desired format.
