### ISSUE TITLE
Pin Operator suggestion

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#479]
Hello Brook,

I cannot find the pin operator in a Spanish keyboard. I do not know if it is hidden in other types of keyboard, but maybe it would be useful to include the information about how to type it.

So far, copy & paste is my friend.

**Comment by BrooklinJazz** [comment]
Hmm, that's frustrating. I'm not sure how to provide instruction on how to type it if your keyboard does not have it.
Normally it's Shift + 6 but that probably won't work on your keyboard.

Can you try typing ALT + 94?

I found a list of codes: https://www.freecodecamp.org/news/alt-codes-special-characters-keyboard-symbols-windows-list/
that may work.

**Comment by BigSpaces** [comment]
Found it in the Spanish keyboard... My apologies for making you look for it.

**Comment by BrooklinJazz** [comment]
All good!
