### ISSUE TITLE
Fix Capitalization Issues In Navigation Script

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#487]
![image](https://user-images.githubusercontent.com/14877564/194823257-5898eb02-0648-401f-9c32-20aae3b8810f.png)

**Comment by BrooklinJazz** [comment]
There's an existing `add_navigation.ex` script in the `utils` folder that contains the script for generating this navigation.

We can modify the `to_title/1` function to include special cases such as `ExUnit`

```elixir
  defp to_title(file_path) do
    file_name =
      case file_path do
        "../reading/" <> file_name -> file_name
        "../exercises/" <> file_name -> file_name
      end

    [name, _extension] = String.split(file_name, ".")

    String.split(name, "_")
    |> Enum.map(&String.capitalize/1)
    |> Enum.join(" ")
  end
```

**Comment by drueck** [comment]
I can take a look at this one today if nobody else is working on it.  :)
