### ISSUE TITLE
Solution in the "Comparison Operators" exercise

### ISSUE THREAD

**Issue by angelmz** [DockYard-Academy/beta_curriculum#496]
**Describe the issue**
There is a solution in the "Comparison Operators" exercise. 
**Reproduction Steps (If Applicable)**
1. Go to 'https://github.com/DockYard-Academy/beta_curriculum/blob/main/reading/comparison_operators.livemd'
2. Scroll down to the third exercise.
3. See error

**Expected behavior**
I can clear the field. It is a small change, I don't know if we are waiting on the script to avoid putting solutions in exercises to fix these.

**Comment by BrooklinJazz** [comment]
Thank you for reporting this! This looks like a great beginner-friendly PR if you or anyone else would like to grab it for their first contribution.

I doubt we'll be able to make a reliable script for catching these issues, but I did open an issue #492 for it in case I ever have some ideas. For now, I think manual intervention is best.

@angelmz It would be very helpful if you can include an image of the solution that should not be part of the exercise. You mentioned on twitter that this is your first time opening an open-source issue, so I also want to say very well done! Reach out if you ever have questions about the project. We're friendly here :D

**Comment by angelmz** [comment]
Thanks Brooklyn, will do!

The third exercise in "Comparison Operator" has it's solution already filled in as shown below.
<img width="1440" alt="Screen Shot 2022-10-11 at 2 12 28 AM" src="https://user-images.githubusercontent.com/49625362/195022233-82a2dff4-b229-4572-b5f6-375768bac941.png">

Also, I later noticed that the last exercise in "Comparison Operators" was missing an input  field so I will go ahead and fix that too.
<img width="1440" alt="Screen Shot 2022-10-11 at 2 12 37 AM" src="https://user-images.githubusercontent.com/49625362/195022296-49db4351-a153-4cf6-84da-f3291f512659.png">

Can't wait to work you all further!
