### ISSUE TITLE
Comparison operator form exercise at the end does not return results after evaluation

### ISSUE THREAD

**Issue by tomireland** [DockYard-Academy/beta_curriculum#5]
## Overview

When evaluating the comparison operator form in the 'Comparison Operators' chapter, after completing it and reevaluating, there is no output to confirm what you entered was correct or not (true or false).

![comparison_operator_form](https://user-images.githubusercontent.com/1268067/154799352-5ea0a6fe-4627-43ea-91a6-4f828e8cb451.png)

## Recreation steps
1. On the code block, select 'Evaluate' to open the form (that's not immediately obvious by the way).
2. Enter the operators into the form fields and once completed, select 'Reevaluate'.

## Behaviour

Confirm there is no output to verify what you entered was correct.

## Expected behaviour

There should be output to verify what you entered was correct.

**Comment by BrooklinJazz** [comment]
addressed in #17
