### ISSUE TITLE
Utils.feedback(:boolean_diagram3, answer) returns false when the diagram looks for true

### ISSUE THREAD

**Issue by w0rd-driven** [DockYard-Academy/beta_curriculum#50]
Stack trace:
```
 1) test boolean_diagram3 (:boolean_diagram3)
     utils/lib/feedback.ex:237
     Assertion with == failed
     code:  assert answer == false
     left:  true
     right: false
     stacktrace:
       utils/lib/feedback.ex:239: (test)
```
I don't believe there's a way to get the diagram to false either way. When I interpret the top-left portion as `true or true` that evaluates to true. It's like `true or` evaluates to true no matter what, only an and would get us into falsey territory.

This screenshot should illustrate this a little better:
<img width="920" alt="Screen Shot 2022-04-14 at 7 07 36 PM" src="https://user-images.githubusercontent.com/489986/163491764-a78d5f7f-3372-4700-88b8-7030a619cb36.png">

**Comment by BrooklinJazz** [comment]
The first `true` should be `false`. This has been adjusted. Thank you for catching this!
