### ISSUE TITLE
I do not seem to be able to use TAB to autocomplete in IEX (Windows 10 - CMD.exe)

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#502]
Hello Brook,

I work in a Windows 10 enterprise, and open IEX using cmd.exe in administrator mode. 

When it comes to using TAB to auto-complete, the prompt simply moves ahead but does not autocomplete. 

I do not know if this is a Windows 10 thing, or a Spanish keyboard thing... happy to jump in and diagnose.

**Comment by BrooklinJazz** [comment]
Apologies for the late comment.

Let's review this during our next review session.
