### ISSUE TITLE
Add the Tom Scott Fizz Buzz video to the Fizz Buzz exercise.

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#519]
https://www.youtube.com/watch?v=QPZ0pIK_wsc&ab_channel=TomScott

We can use the `YouTube` module to embed a youtube video.

```elixir
YouTube.new("https://www.youtube.com/watch?v=QPZ0pIK_wsc&ab_channel=TomScott")
```

Include this inside of a HiddenCell Smart Cell. You can create a smart cell by pressing the + Smart Cell button.

![image](https://user-images.githubusercontent.com/14877564/195959664-1cdc06a6-4366-447b-a3c3-135901171bb1.png)

Double-click the Hidden Cell to reveal the editor. Replace the title with FizzBuzz and enter the code inside the text area.

![image](https://user-images.githubusercontent.com/14877564/195959756-47aeefea-7155-462a-8d02-4c3bc7fb5d66.png)

Make sure the video appears.

![image](https://user-images.githubusercontent.com/14877564/195959789-950f0364-19f4-4978-89b1-38e5a2fce54b.png)

**Comment by aryanlath** [comment]
Hi! Can you assign this to me?

**Comment by BrooklinJazz** [comment]
Feel free to make a PR! On mobile rn and about to sleep so cannot assign it, but your comment above will serve as "dibs" 👍

**Comment by aryanlath** [comment]
<img width="1440" alt="Screenshot 2022-10-17 at 12 00 13 AM" src="https://user-images.githubusercontent.com/99634099/196051958-1a498d98-698e-43f5-a3fe-f97953f3112d.png">
Hi! I am getting this error while running Mix.install cell

**Comment by aryanlath** [comment]
If possible can you provide me with a solution to this?

**Comment by BrooklinJazz** [comment]
Some folks have been getting this error because of the `utils` project. We're moving towards fixing this by removing `utils` entirely in #523. For now, the temporary workaround is to comment the `utils` project in the setup section.
```elixir
Mix.install([
  {:youtube, github: "brooklinjazz/youtube"},
  {:hidden_cell, github: "brooklinjazz/hidden_cell"},
  {:tested_cell, github: "brooklinjazz/tested_cell"},
  # {:utils, path: "#{__DIR__}/../utils"}
])
```

Just make sure you don't commit this change in a PR.

**Comment by aryanlath** [comment]
I have taken care of all the changes and carefully added the video. Kindly check my pull request.
