### ISSUE TITLE
Remove `utils` project

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#523]
We are incredibly close to being able to remove the `utils` project from the curriculum.

We need to
- [ ] Remove all calls to Utils.* module.
- [ ] Remove installation of `utils` project in the setup section of each livebook.

We still want to keep the `utils` project for development purposes, but each livebook should no longer rely on it. This means that each livebook can run independently, and be imported into livebook individually without the `utils` project installed locally.

**Comment by drueck** [comment]
I'd be interested in taking a look at this one, unless someone else wanted to work on it. I started looking at it, and noticed one of the main usages of `Utils` is the `feedback` function, which as I understand it inserts tests for a given exercise. Would we just inline those tests instead?

**Comment by BrooklinJazz** [comment]
We've moved away from using Utils.feedback (It's almost 100% removed). I think it's mostly in deprecated files that are no longer part of the course.

For most cases, we've moved to using example solutions for simple exercises, and doctests for bigger ones (Livebook is working on  a feature to automatically run doctests in modules)

Anything else can be a HiddenCell (click on the +SmartCell button and select hidden cell) The hidden cell can hide some code for the sake of powering a visual.

**Comment by BrooklinJazz** [comment]
The CONTRIBUTING.md file has examples of using Hints and Example Solution blocks in markdown.

We also have example doctests.

This Issue is open if you want to submit a PR for it!

**Comment by drueck** [comment]
Ah, gotcha. Thanks for the clarification on that. I noticed just via a global search of the codebase a lot of usages of `Utils.feedback`, but I didn't realize there were so many deprecated exercises. If an exercise is not listed in the outline in `start.livemd`, does that mean it's deprecated, or is it possible some are missing from the outline? If they are deprecated, should we delete them?

**Comment by BrooklinJazz** [comment]
I don't want to delete exercises as they may be useful for bonus exercises or I may add them in later.

I have a `removed_content_tracking.md` file that tracks any content I've temporarily removed from the outline that I plan to add back. Any content not in there and not in the outline is probably fine to remove, but I plan to do that once the outline is more settled.

**Comment by drueck** [comment]
That makes sense. In that case I will ignore usages of `Utils` in the exercises that are likely to be deleted I guess, and just update the ones that are actively in the course or in `removed_content_tracking.md` as ones that will possibly be added back. 👍
