### ISSUE TITLE
Question about prompting options.

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#525]
Hello Brook,

Not really an issue, more of a question. In Rock/Paper/Scissors, in the module, it reads: 

The game should prompt the user for a choice of "rock", "paper", or "scissors".

I am not clear if I am supposed to create code that would prompt "options", such as "enter R for rock" or "enter 1 for rock". Or if it is just an IO.gets without any pre-validated options.

I will move on with a simple IO.gets() :D

**Comment by BrooklinJazz** [comment]
IO.gets is perfectly valid :) Though using 1, 2, 3 would be an interesting bonus!
