### ISSUE TITLE
Wordle test cases are incorrect

### ISSUE THREAD

**Issue by SRFowler** [DockYard-Academy/beta_curriculum#530]
At least one test case in wordle (exercises/wordle_application.livemd) are incorrect. 

**Expected behavior**
For a case where a letter in both the word and guess are at the same ordinal position the test should expect a `:green` atom.
In the third test `Games.World.feedback("abcde", "edcba")` the letter "c" is in the same position in each word so the test should read `[:yellow, :yellow, :green, :yellow, :yellow]`.  
  
The final test implies that the letter "x" does not appear in the answer; this letter should be :yellow as it exists in the answer in a different position.  
```elixir
iex> Games.World.feedback("aaaxx", "xaaaa")
[:grey, :green, :green, :yellow, :grey]
```
Should read:
```elixir
iex> Games.World.feedback("aaaxx", "xaaaa")
[:yellow, :green, :green, :yellow, :grey]
```

**Screenshots**

**Comment by BrooklinJazz** [comment]
Good catch, I'll fix this now.
