### ISSUE TITLE
Some of the links to Faker are broken.

### ISSUE THREAD

**Issue by threetriangles** [DockYard-Academy/beta_curriculum#535]
A few of the documentation links to Faker are broken

**Comment by BrooklinJazz** [comment]
For anyone wanting to work on this, try doing a find all search for

`https://hexdocs.pm/elixir/Faker.html`

I believe it should be `https://hexdocs.pm/faker/readme.html`

**Comment by dmarcoux** [comment]
This issue should be closed.
