### ISSUE TITLE
Lucas number assignment

### ISSUE THREAD

**Issue by threetriangles** [DockYard-Academy/beta_curriculum#544]
The base case needs to be defined for the Lucas number.
L(0) = 2
L(1) = 1

**Comment by BrooklinJazz** [comment]
The same is true for fibonacci

**Comment by BrooklinJazz** [comment]
While doing this, I'd like to add a bonus to the Lucas number assignment to use recursion to solve the `sequence/1` problem. (Instead of something like `Enum.map/2`.
