### ISSUE TITLE
Streams "Your Turn" example missing "end"

### ISSUE THREAD

**Issue by SRFowler** [DockYard-Academy/beta_curriculum#553]
In the file reading/streams.livemd in the "Your Turn" section the example Enum calls to be refactored are malformed. 
```elixir
1..100
|> Enum.map(fn each -> div(each, 2))
|> Enum.map(fn each -> each * 3)
|> Enum.filter(fn each -> rem(each, 2) === 0)
```
Should read
```elixir
1..100
|> Enum.map(fn each -> div(each, 2) end)
|> Enum.map(fn each -> each * 3 end)
|> Enum.filter(fn each -> rem(each, 2) === 0 end)
```  
  
Feel free to mark this issue complete and leave troubleshooting as an exercise for the reader.

**Comment by BrooklinJazz** [comment]
Fixing this in my next PR. Troubleshooting a bug like that would make for an interesting exercise in a future debugging section 🤔
