### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#562]
Hello @BrooklinJazz 

I read this in the document: 

Implement the StreamProducts module using Streams instead of the [Enum](https://hexdocs.pm/elixir/Enum.html) module.

But this is MapSets. I imagine it is something to update from the previous document.

Hope it helps!

**Comment by BrooklinJazz** [comment]
Thank you! I'll have a fix in my next PR.
