### ISSUE TITLE
Supervisor examples crashing my Livebook - And a couple of ideas

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#584]
Hello Brook,

May be worth troubleshooting this one. I have not modified the code in the cells but I cannot make the examples run in the way it is described in the document.

![Elixir Processes Supervisors-1667726884454](https://user-images.githubusercontent.com/113518695/200163536-155caead-0b70-49b2-a344-d39bf3439f26.jpeg)
![Elixir Processes Supervisors-1667726954790](https://user-images.githubusercontent.com/113518695/200163537-94e5e1d0-89bc-45e2-956d-e002ec69d0f4.jpeg)

If you would like to troubleshoot together, I am sure I could learn quite a lot from seeing you go through the process. I could also let you know how the concepts land in the mind of a beginner, and that may provide ideas on how to unpack complex concepts such as GenServers, Asynchronous messages, and Supervisors.

I find myself reordering the topics and finding where the text assumes knowledge that I do not yet have. All the pieces are there, but I feel the ordering and the exposition of certain ideas could use some re-sequencing and fine tuning. It is difficult to say if this is just me and my learning style or if it is something more objectively true about how the document is presenting certain topics. Maybe something to ask the cohort and gather feedback.

IDEA: How about linking to a Google Form at the end of each lesson to gather feedback from the students? This could provide a first layer of information on the strengths and weaknesses of each document.

Thanks, Brook. See ya later!

Jon

**Comment by BrooklinJazz** [comment]
Resolved the issue with Jon in person.
