### ISSUE TITLE
Notes on Tasks (Typos)

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#598]
Hello @BrooklinJazz ,

#### Typos

> Instead, we should **instead** rely on the [Task](https://hexdocs.pm/elixir/Task.html) module.

> A computer with a multi-core processor can perform these **cpmcirremt** computations in parallel,

> Alernatively, you can use the convenient *Taskl*.await_many/1 function instead.

Hope it helps!

**Comment by gcavanunez** [comment]
These typos have already been taken cared of right? Taking a look at the files/prs, seems to have been corrected via 
- #599

**Comment by BrooklinJazz** [comment]
Yup!
