### ISSUE TITLE
Improve chapter navigation

### ISSUE THREAD

**Issue by tomireland** [DockYard-Academy/beta_curriculum#6]
At this moment in time, there is no way to get to instructions.md (the chapter list), navigate back and forth between chapters or jump to the top of the page (unless you expand sections). I have to hit the back button in my browser to get back to the contents page. Might be a local server limitation as not overly familiar with Livebook and how navigation works but good to let you know about.

**Comment by BrooklinJazz** [comment]
I agree. I'm looking for a solution but I think it will be on Livebook's side. I could put a link at the top of every page that 
Has a link back to the `instructions.livemd` 🤔

**Comment by auranykh** [comment]
@BrooklinJazz - if possible would you mind if I take this on when I have some time? My thinking would similar but just adding a Home link to the top of each page for now. Livebook could likely benefit from a breadcrumb style layout as well, but as you said, a more thorough solution would likely be on their end.

**Comment by BrooklinJazz** [comment]
If you want to tackle this it would be greatly appreciated!
A home link for now that takes you to start.livemd would be excellent.

**Comment by auranykh** [comment]
PR #30 submitted to add navigation.

**Comment by BrooklinJazz** [comment]
PR #30 Resolves this issue. Thank you @auranykh!

I believe Livebook is updating the GUI which may (I hope) improve navigation in general.
