### ISSUE TITLE
Suggested clarifications to Book Search: Books (Associations) content

### ISSUE THREAD

**Issue by GumptionWare** [DockYard-Academy/beta_curriculum#653]
Our group was slightly confused by the first portion of the **BookSearch** "Your Turn" content being in the middle of the Associations lesson material. (Perhaps "jarring" is a better description of how it hit us.)

All of the content between "**BookSearch: Books**" and "**Building Associations**" is really "Your Turn" content (student exercises), and we figured that out, but then the content jumped back into instructional content until (suddenly) "**Fix Failing Context Tests**" (more "Your Turn" exercises).

Given the pattern in most other lessons of contiguous instructional content. followed by contiguous "Your Turn" student exercise material, we felt that this lesson added some friction to the learning process. We suggest sticking with that pattern to reduce this friction.

Feel free to ask other groups if they had a similar experience. If not, please dismiss this as another Helmanism.

**Comment by BrooklinJazz** [comment]
I've significantly simplified the content and I think it accomplishes what you're after, so I will close this issue.

Feel free to re-raise an issue if you think there are further improvements to be made.
