### ISSUE TITLE
Integers/maths exercise does not return results after evaluation

### ISSUE THREAD

**Issue by tomireland** [DockYard-Academy/beta_curriculum#7]
## Overview

Similar to the issue reported in #5 , the Integer forms do not appear to evaluate the values input by the learner even after choosing reevaluate.

![integers_exercise](https://user-images.githubusercontent.com/1268067/154800322-a5c37512-ca93-44ee-bf2a-6e8b421df951.png)

Similarly, when doing the arithmetic exercises, there is no confirmation of what the answer should be, so it's hard to verify what you did was correct or not (without doing the maths yourself :slightly_smiling_face:). I think that seeing the answer you expect to return would help you figure out the right way to do the work. For example, if you had to do 10 divided by 3 and the answer expected was `3.3333333333333335`, then you know you need to do `10 / 3` as opposed to `div(10, 3)` because the latter does not result in a floating point number. Helps cement the learning, unless I'm misinterpreting it?

## Recreation steps
1. On the code block, select 'Evaluate' to open the form.
2. Enter a value into the form field and once completed, select 'Reevaluate'.

## Behaviour

Confirm there is no output to verify what you entered was correct.

## Expected behaviour

There should be output to verify what you entered was correct.

**Comment by BrooklinJazz** [comment]
I agree! Right now there's not a good feedback system. This will be part of the larger plan to improve feedback for exercises in general.

**Comment by BrooklinJazz** [comment]
I've created a new validated form widget that should be a perfect fit for this

**Comment by BrooklinJazz** [comment]
These exercises have been replaced. Closing
